# Generated by Django 3.0.2 on 2020-01-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='Grape',
            new_name='grape',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='Winery',
            new_name='winery',
        ),
        migrations.RenameField(
            model_name='bottle',
            old_name='Year',
            new_name='year',
        ),
    ]
