# Generated by Django 3.0.2 on 2020-01-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wine_app', '0002_auto_20200122_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottle',
            old_name='user',
            new_name='author',
        ),
    ]
